name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Find gradlew
      run: |
        echo "Searching for gradlew..."
        find . -name "gradlew"
    
    - name: Grant execute permission to Gradle
      run: |
        GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
        if [ -z "$GRADLEW_PATH" ]; then
          echo "Error: gradlew not found!" >&2
          exit 1
        fi
        chmod +x "$GRADLEW_PATH"
        echo "Using gradlew at $GRADLEW_PATH"
    
    - name: Build APK
      run: |
        GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
        "$GRADLEW_PATH" assembleRelease --stacktrace
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-release
        path: app/build/outputs/apk/release/*.apk

    - name: List available artifacts
      run: ls -R $GITHUB_WORKSPACE

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: apk-release
        path: downloaded-artifacts


