- name: Cache
  uses: actions/cache@v4.2.3
  with:
    path: null
    key: null
    restore-keys: null
    upload-chunk-size: null
    enableCrossOsArchive: null
    fail-on-cache-miss: null
    lookup-only: null
    save-always:
      - name: Setup Node.js environment
  -uses: actions/setup-node@v4.3.0
  -with:
    always-auth: null
    node-version: null
    node-version-file: null
    architecture: null
    check-latest: null
    registry-url: null
    scope: null
    token: null
    cache: null
    cache-dependency-path:
      - name: Upload a Build Artifact
    -uses: actions/upload-artifact@v4.6.2
    with: null
    name: null
    path: null
  Available Options:
    warn: Output a warning but do not fail the action
    error: Fail the action with an error message
    ignore: Do not output any warnings or errors, the action does not fail
    if-no-files-found: Minimum 1 day. Maximum 90 days unless changed from the
      repository settings page.
    retention-days: null
    compression-level: null
    overwrite: null
    include-hidden-files:
      - name: Download a Build Artifact
    uses: actions/download-artifact@v4.2.1
    with: null
    name: null
    path: null
    pattern: null
    merge-multiple: null
    github-token: null
    repository: null
    run-id:
      - name: Setup Go environment
    -uses: actions/setup-go@v5.4.0
    -with: null
    go-version: null
    go-version-file: null
    check-latest: null
    token: null
    cache: null
    cache-dependency-path: null
    architecture: null
